import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getPrescription } from '../utils/expertSystem';
import './Prescription.css';

const Prescription = () => {
  const navigate = useNavigate();
  const [prescriptionData, setPrescriptionData] = useState(null);
  const [selectedSymptoms, setSelectedSymptoms] = useState([]);

  useEffect(() => {
    const storedSymptoms = sessionStorage.getItem('selectedSymptoms');
    if (storedSymptoms) {
      const symptoms = JSON.parse(storedSymptoms);
      setSelectedSymptoms(symptoms);
      const data = getPrescription(symptoms);
      setPrescriptionData(data);
    } else {
      // If no symptoms, redirect to symptom checker
      navigate('/symptom-checker');
    }
  }, [navigate]);

  const handlePrint = () => {
    window.print();
  };

  const handleNewCheck = () => {
    sessionStorage.removeItem('selectedSymptoms');
    navigate('/symptom-checker');
  };

  if (!prescriptionData) {
    return (
      <div className="prescription-loading">
        <div className="loading-spinner"></div>
        <p>Loading prescription...</p>
      </div>
    );
  }

  return (
    <div className="prescription">
      <div className="container">
        <div className="prescription-header">
          <h1 className="page-title">Your Prescription</h1>
          <div className="prescription-actions">
            <button onClick={handleNewCheck} className="btn btn-secondary">
              New Check
            </button>
            <button onClick={handlePrint} className="btn btn-primary">
              Print Prescription
            </button>
          </div>
        </div>

        <div className="prescription-info">
          <div className="info-card">
            <h3>Patient Information</h3>
            <p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
            <p><strong>Symptoms:</strong> {selectedSymptoms.length}</p>
          </div>
        </div>

        <div className="prescription-content">
          <div className="medicines-section">
            <h2>Prescribed Medicines</h2>
            {prescriptionData.prescriptions.map((medicine, index) => (
              <div key={index} className="medicine-card">
                <div className="medicine-header">
                  <h3>{medicine.name}</h3>
                  <span className="medicine-badge">Prescribed</span>
                </div>
                <div className="medicine-details">
                  <div className="detail-item">
                    <span className="detail-label">Dosage:</span>
                    <span className="detail-value">{medicine.dosage}</span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Frequency:</span>
                    <span className="detail-value">{medicine.frequency}</span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Duration:</span>
                    <span className="detail-value">{medicine.duration}</span>
                  </div>
                  {medicine.symptoms && medicine.symptoms.length > 0 && (
                    <div className="detail-item">
                      <span className="detail-label">For Symptoms:</span>
                      <span className="detail-value">
                        {medicine.symptoms.join(', ')}
                      </span>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>

          <div className="symptoms-section">
            <h2>Symptom Details</h2>
            {prescriptionData.symptomDetails.map((item, index) => (
              <div key={index} className="symptom-detail-card">
                <h3>{item.symptom}</h3>
                <p className="symptom-description">{item.data.description}</p>
                <div className="severity-badge">
                  Severity: <span className={`severity-${item.data.severity}`}>
                    {item.data.severity.charAt(0).toUpperCase() + item.data.severity.slice(1)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="prescription-warning">
          <div className="warning-icon">⚠️</div>
          <div className="warning-content">
            <h3>Important Disclaimer</h3>
            <p>
              This prescription is generated by an expert system for informational purposes only. 
              Always consult with a qualified healthcare professional before taking any medication. 
              Do not self-medicate without proper medical advice. If symptoms persist or worsen, 
              seek immediate medical attention.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Prescription;

